FriendFeed/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from groups import views
from questions import views as v


urlpatterns = [
    path('admin/', admin.site.urls),
	path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
	path('index/',TemplateView.as_view(template_name="index.html"), name="index"),
	path('',views.GroupList.as_view(),name='home'),
	path('groups/', include('groups.urls')),
	path('questions/', include('questions.urls')),
	path('create/question/', v.CreateQuestion.as_view(), name='create_question'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views
from questions import views as v
from django.conf import settings
from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),
         name='login'), 
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.Signup.as_view(), name='signup'),
    path('<slug>/', v.UserProfileQuestion, name='profile'),
    #path('<slug>/', v.UserProfile.as_view(), name='profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

groups/urls.py
from django.urls import path
from groups import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'groups'

urlpatterns = [
    path('<slug>/', views.GroupDetail.as_view(), name='single'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

questions/urls.py
from django.urls import path
from questions import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'questions'

urlpatterns = [
    path('detail/<slug>/', views.QuestionDetail.as_view(), name='question_single'),
    path('<slug>/delete/', views.DeleteQuestion.as_view(), name='delete_question'),
    path('<slug>/update/', views.UpdateQuestion.as_view(), name='update_question'),
    path('remove/answer/<pk>/', views.DeleteAnswer.as_view(), name='remove_answer'),
    path('<slug>/solved', views.question_solved, name='question_solved'),
    path('answer/<pk>/upvote', views.upvote, name='upvote'),
    path('answer/<pk>', views.DetailAnswer.as_view(), name='ans_single'),
    path('results/', views.SearchQuests, name="search_quests"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

questions/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse
from groups.models import Group


class Question(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='questions', on_delete=models.PROTECT)
    group = models.ForeignKey(
        Group, related_name='questions', on_delete=models.CASCADE)
    name = models.CharField(max_length=500)
    body = models.TextField(blank=True)
    created_date = models.DateTimeField(auto_now=True)
    solved = models.BooleanField(default=False)
    slug = models.SlugField(allow_unicode=True, unique=True)

    def __str__(self):
        return self.name

    def question_solved(self):
        self.solved = True
        self.save()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('questions:question_single', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['-created_date']


class Answer(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='answers', on_delete=models.PROTECT)
    question = models.ForeignKey(
        'questions.Question', related_name='answers', on_delete=models.CASCADE)
    body = models.CharField(max_length=200)
    likes = models.PositiveIntegerField(default=0)
    created_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.body

    def get_absolute_url(self):
        return reverse('question:question_detail', kwargs={'slug': self.question.slug})

    class Meta:
        ordering = ['-likes']

questions/forms.py
from django import forms
from questions.models import Question, Answer
from accounts.models import User


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('group', 'name', 'body',)


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('body', 'question', 'author')
        widgets = {'question': forms.HiddenInput(
        ), 'author': forms.HiddenInput()}

questions/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import FormMixin
from django.views.generic.list import MultipleObjectMixin
from django.core.paginator import Paginator
from questions.models import Question, Answer
from accounts.models import User
from questions.forms import QuestionForm, AnswerForm
from django.http import Http404
from django.db.models import Q
from django.contrib.auth import get_user_model
User = get_user_model()


class QuestionList(ListView):
    model = Question
    template_name = 'questions/_question.html'


class QuestionDetail(FormMixin, DetailView):
    model = Question
    form_class = AnswerForm

    def get_success_url(self):
        return reverse('questions:question_single', kwargs={'slug': self.object.slug})

    def get_context_data(self, **kwargs):
        context = super(QuestionDetail, self).get_context_data(**kwargs)
        context['form'] = AnswerForm(
            initial={'question': self.object, 'author': self.request.user})
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        return super(QuestionDetail, self).form_valid(form)


class CreateQuestion(LoginRequiredMixin, CreateView):
    model = Question
    form_class = QuestionForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user  # connect post to a user
        self.object.save()
        return super().form_valid(form)


class DeleteQuestion(LoginRequiredMixin, DeleteView):
    model = Question
    success_url = reverse_lazy('home')


class UpdateQuestion(LoginRequiredMixin, UpdateView):
    model = Question
    form_class = QuestionForm
    template_name_suffix = '_update_form'


class DeleteAnswer(LoginRequiredMixin, DeleteView):
    model = Answer
    success_url = reverse_lazy('home')


class DetailAnswer(DetailView):
    model = Answer
    template_name = 'questions/answer_detail.html'

@login_required
def SearchQuests(request):
    if request.method == 'GET':
        query = request.GET.get('q')

        results = Question.objects.filter(name__icontains=query)

        return render(request, 'questions/question_list.html', {'results': results})
    else:
        return render(request, 'questions/question_list.html')

@login_required
def UserProfileQuestion(request, slug):
    user = User.objects.get(slug=slug)
    user_question = Question.objects.filter(
        author=user).order_by('-created_date')
    paginator = Paginator(user_question, 2)
    page = request.GET.get('page')
    questions = paginator.get_page(page)

    user_answer = Answer.objects.filter(author=user).order_by('-created_date')

    paginatorAnswer = Paginator(user_answer, 3)
    pageAns = request.GET.get('page2')
    answers = paginatorAnswer.get_page(pageAns)

    return render(request, 'questions/user_profile.html', {'user_question': questions, 'user_answer': answers, 'user': user})


@login_required
def question_solved(request, slug):
    question = get_object_or_404(Question, slug=slug)
    question.question_solved()
    return redirect('questions:question_single', slug=question.slug)


@login_required
def upvote(request, pk):
    answer = get_object_or_404(Answer, pk=pk)
    answer.likes += 1
    answer.save()
    return redirect('questions:question_single', slug=answer.question.slug)

questions/templates/questions/_answer.html
{% for answer in user_answer %}

{{answer.body}}

{% endfor %}

questions/templates/questions/_question.html
<h2>Questions</h2>
{% for question in user_question %}

{{question.name}}
{{question.author}}
{{question.body}}

{% endfor %}
<h2>Answers</h2>
{% for answer in user_answer %}

{{answer.body}}

{% endfor %}

questions/templates/questions/answer_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Delete {{question.title}}</h1>
<form method="POST">
  {% csrf_token %}
  <p>Are you sure you want to delete your answer?</p>
  <hr>
  <p>
   {{ object }}
  </p>
  <input type="submit" class="btn btn-sm btn-danger" value="Delete">
</form>
{% endblock %}

questions/templates/questions/answer_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <div class="jumbotron">
    <h5 class="font-weight-bold">Question</h5>
    <p>
      {{answer.question.name}}
    </p>
    <h6 class="font-weight-bold">Answer</h6>
    <p>
      {{answer.body}}
    </p>
    <div class="btn-group btn-group-sm">
      {% if user.is_authenticated %}
      <a href="javascript:{document.getElementById('upvote').submit()}"><button class="btn btn-primary btn-sm">Upvote
          this
          answer</button></a>
      {% endif %}

      <a href="{% url 'questions:question_single' slug=answer.question.slug %}" class="btn btn-warning btn-sm">Back to
        Question</a>

      <form id="upvote" method="POST" action="{% url 'questions:upvote' pk=answer.pk %}">
        {% csrf_token %}
        <input type="hidden">
      </form>

      <br />
      {% if user.is_authenticated and answer.author == user %}
      <a href="{% url 'questions:remove_answer' pk=answer.pk %}" class="btn btn-sm btn-danger">Delete</a>
      {% endif %}
    </div>
  </div>
</div>


{% endblock %}

questions/templates/questions/question_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Delete {{question.title}}</h1>
<form method="POST">
  {% csrf_token %}
  <p>Are you sure you want to delete {{object}}</p> <!-- something in delete view the object injection -->
  <input type="submit" class="btn btn-danger btn-sm" value="Delete">
</form>
{% endblock %}

questions/templates/questions/question_detail.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
{% load static %}
<hr>
<blockquote class="blockquote bq-primary">
  <p class="bq-title">{{ question.name }}</p>
  <p>{{question.body}}
  </p>
  <div class="">
    <h6>Published on: <strong>{{question.created_date}}</strong> by:<a
        href="{% url 'accounts:profile' slug=question.author.slug %}"> {{ question.author }}</a> </h6>
  </div>
  <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
    {% if question.author == user %}
    <a href="{% url 'questions:update_question' slug=question.slug %}"
      class="btn btn-sm btn-warning text-dark font-weight-bold">Edit Quiz</a>
    <a href="{% url 'questions:delete_question' slug=question.slug %}"
      class="btn btn-sm btn-danger text-dark font-weight-bold">Delete Quiz</a>
    {% endif %}
    {% if question.author == user and question.solved == False %}
    <a class="btn btn-sm btn-success text-dark font-weight-bold"
      href="{% url 'questions:question_solved' slug=question.slug %}">Mark Solved</a>
    {% endif %}
  </div>
</blockquote>
<hr>

</div>
<div class='container'>
  <h2 class="font-weight-bold">Answers provided for this question</h2>

  {% if question.solved %}
  <h5>Question has been solved </h5>
  {% for answer in question.answers.all|slice:":10" %}
  {{answer.body}}
  <a href="{% url 'questions:ans_single' pk=answer.pk %}">​<i class="fa fa-thumbs-o-up" style="font-size:36px"></i></a>
  <p>Author: {{answer.author}} Upvotes: {{answer.likes}}</p>
  {% endfor %}
  {% else %}
  {% for answer in question.answers.all %}
  <br>
  <hr>
  <strong>Answer:</strong> <p>{{answer.body}}</p>
  <p>By: <strong>{{answer.author}}</strong> <br> Upvotes: <strong> {{answer.likes}}</strong></p>
  <a class="btn btn-sm btn-dark-green" href="{% url 'questions:ans_single' pk=answer.pk %}">Upvote Answer</a>
<hr>
  {% endfor %}

  <h6 class="font-weight-light">This Question has not been solved yet. <br> Provide your answer below.</h6>

  {% endif %}
</div>



{% if user.is_authenticated and question.solved == False %}
<div class='container'>
  <div class="row">
    <div class="col-lg-6">
      <form method='POST'>
        {% csrf_token %}
        {{ form.as_p}}
        <input type="Submit" class="btn btn-sm btn-dark-green" value="Add Answer">
      </form>
    </div>
  </div>

</div>
{% endif %}

{% endblock %}

questions/templates/questions/question_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<h1 class="text-center">Ask a New Question</h1>
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-lg-6">
      <form method='POST' enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form form %}
  
  <input type="Submit" class="btn btn-success btn-sm" value="Ask Question">
</form>
    </div>
  </div>
</div>


{% endblock %}

questions/templates/questions/question_list.html
{% extends 'base.html' %}

{% block content%}
{% for question in results %}
<div class="container">
  <div class="jumbotron mt-5">
    <h4 class="text-center">Results for Questions containing the searched term</h4>
    <ul class="list">
      <a class="btn btn-elegant btn-sm" href="{% url 'questions:question_single' slug=question.slug %}">{{ question.name }}</a>
    </ul>
  </div>
</div>

{% endfor %}

{% endblock %}
{% extends 'base.html' %}
{% block content %}
<h3 class="text-center">{{user.username}} 's profile</h3>
<hr>
<div class="container">
    <!-- Card -->
    <div class="card testimonial-card">

        <!-- Background color -->
        <div class="card-up"></div>

        <!-- Avatar -->
        <div class="avatar mx-auto white">
            <img src="{{user.image.url}}" width="200px" height="200px" class="mt-3 mb-3 rounded-circle" alt="avatar">
        </div>

        <!-- Content -->
        <div class="card-body">
            <!-- Name -->
            <h4 class="font-weight-bold text-center card-title">{{user.username}}</h4>
            <!-- Quotation -->
            <p class="text-center">{{ user.bio }}</p>
            <hr>

            <h2>Questions Asked </h2>

            {% for question in user_question %}
            <ul>
                <li>
                    <a href="{% url 'questions:question_single' slug=question.slug%}">{{question.body}}</a>
                </li>
            </ul>
            {% endfor %}
            <hr>

            <h2>Questions Answered</h2>
            {% for answer in user_answer %}
            <ul>
                <li>
                    <a href="{% url 'questions:question_single' slug=answer.question.slug %}">{{answer.body}}</a>
                </li>
            </ul>
            {% endfor %}
            <hr>
        </div>
    </div>
    <!-- Card -->
</div>

<div class="pagination">
    <span class="step-links">
        {% if user_question.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ user_question.previous_page_number }}">previous</a>
        {% endif %}
{% extends 'base.html' %}
{% block content %}
<h3 class="text-center">{{user.username}} 's profile</h3>
<hr>
<div class="container">
    <!-- Card -->
    <div class="card testimonial-card">

        <!-- Background color -->
        <div class="card-up"></div>

        <!-- Avatar -->
        <div class="avatar mx-auto white">
            <img src="{{user.image.url}}" width="200px" height="200px" class="mt-3 mb-3 rounded-circle" alt="avatar">
        </div>

        <!-- Content -->
        <div class="card-body">
            <!-- Name -->
            <h4 class="font-weight-bold text-center card-title">{{user.username}}</h4>
            <!-- Quotation -->
            <p class="text-center">{{ user.bio }}</p>
            <hr>

            <h2>Questions Asked </h2>

            {% for question in user_question %}
            <ul>
                <li>
                    <a href="{% url 'questions:question_single' slug=question.slug%}">{{question.name}}</a>
                </li>
            </ul>
            {% endfor %}
            <hr>

            <h2>Questions Answered</h2>
            {% for answer in user_answer %}
            <ul>
                <li>
                    <a href="{% url 'questions:question_single' slug=answer.question.slug %}">{{answer.body}}</a>
                </li>
            </ul>
            {% endfor %}
            <hr>
        </div>
    </div>
    <!-- Card -->
</div>

<div class="pagination">
    <span class="step-links">
        {% if user_question.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ user_question.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ user_question.number }} of {{ user_question.paginator.num_pages }}
        </span>

        {% if user_question.has_next %}
        <a href="?page={{ user_question.next_page_number }}">next</a>
        <a href="?page={{ user_question.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}
        <span class="current">
            Page {{ user_question.number }} of {{ user_question.paginator.num_pages }}
        </span>

        {% if user_question.has_next %}
        <a href="?page={{ user_question.next_page_number }}">next</a>
        <a href="?page={{ user_question.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

questions/templates/questions/question_update_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<h2>Edit the Question and save your changes</h2>
<form method='POST' enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="Submit" class="btn btn-success btn-sm" value="Save Changes">
</form>

{% endblock %}

questions/templates/questions/user_profile.html
{% extends 'base.html' %}
{% block content %}
<h3 class="text-center">{{user.username}} 's profile</h3>
<hr>
<div class="container">
    <!-- Card -->
    <div class="card testimonial-card">

        <!-- Background color -->
        <div class="card-up"></div>

        <!-- Avatar -->
        <div class="avatar mx-auto white">
            <img src="{{user.image.url}}" width="200px" height="200px" class="mt-3 mb-3 rounded-circle" alt="avatar">
        </div>

        <!-- Content -->
        <div class="card-body">
            <!-- Name -->
            <h4 class="font-weight-bold text-center card-title">{{user.username}}</h4>
            <!-- Quotation -->
            <p class="text-center">{{ user.bio }}</p>
            <hr>

            <h2>Questions Asked </h2>

            {% for question in user_question %}
            <ul>
                <li>
                    <a href="{% url 'questions:question_single' slug=question.slug%}">{{question.name}}</a>
                </li>
            </ul>
            {% endfor %}
            <hr>

            <h2>Questions Answered</h2>
            {% for answer in user_answer %}
            <ul>
                <li>
                    <a href="{% url 'questions:question_single' slug=answer.question.slug %}">{{answer.body}}</a>
                </li>
            </ul>
            {% endfor %}
            <hr>
        </div>
    </div>
    <!-- Card -->
</div>

<div class="pagination">
    <span class="step-links">
        {% if user_question.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ user_question.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ user_question.number }} of {{ user_question.paginator.num_pages }}
        </span>

        {% if user_question.has_next %}
        <a href="?page={{ user_question.next_page_number }}">next</a>
        <a href="?page={{ user_question.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}