FriendFeed/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from groups import views
from questions import views as v


urlpatterns = [
    path('admin/', admin.site.urls),
	path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
	path('index/',TemplateView.as_view(template_name="index.html"), name="index"),
	path('',views.GroupList.as_view(),name='home'),
	path('groups/', include('groups.urls')),
	path('questions/', include('questions.urls')),
	path('create/question/', v.CreateQuestion.as_view(), name='create_question'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groups/urls.py
from django.urls import path
from groups import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'groups'

urlpatterns = [
    path('<slug>/', views.GroupDetail.as_view(), name='single'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

questions/urls.py
from django.urls import path
from questions import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'questions'

urlpatterns = [
    path('detail/<slug>/', views.QuestionDetail.as_view(), name='question_single'),
    path('<slug>/delete/', views.DeleteQuestion.as_view(), name='delete_question'),
    path('<slug>/update/', views.UpdateQuestion.as_view(), name='update_question'),
    path('remove/answer/<pk>/', views.DeleteAnswer.as_view(), name='remove_answer'),
    path('<slug>/solved', views.question_solved, name='question_solved'),
    path('answer/<pk>/upvote', views.upvote, name='upvote'),
    path('answer/<pk>', views.DetailAnswer.as_view(), name='ans_single'),
    path('results/', views.SearchQuests, name="search_quests"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

groups/models.py
from django.db import models
from django.utils.text import slugify


class Group(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(default='DEFAULT VALUE')
    slug = models.SlugField(allow_unicode=True, unique=True)
    image = models.ImageField(upload_to='groups/', blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

groups/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from groups.models import Group


class GroupList(ListView):
    model = Group


class GroupDetail(DetailView):
    model = Group

groups/templates/groups/group_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container text-center jumbotron mt-3">
  <h1 class="font-weight-bold">{{group.name}}</h1> <hr>
  <h2>{{group.description}}</h2>
</div>

{% if group.questions.count == 0 %}
<div class="container text-center">
  <h4>There are no Questions in this Group. Be the first to <a class="btn btn-dark-green btn-sm" href="{% url 'create_question' %}">Ask a Question</a></h4>

  {% else %}
  <h3 class="text-center font-weight-bold">
    Recently asked questions
  </h3>
  {% for question in group.questions.all %}
  <!-- Need for loop to go through each one -->
  <ul>
    <li class="font-weight-bold"><a href="{% url 'questions:question_single' slug=question.slug %}">{{question.name}}</a></li>
  </ul>
  <!-- This is used to inject a html file into the middle of this block, similar to extends -->
  {% endfor %}
  {% endif %}
</div>

{% endblock %}

groups/templates/groups/group_list.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <div class="row">
    {% for group in group_list %}
    <div class="col-lg-3 col-md-12 text-center" id="groups-list">
      <a href="{% url 'groups:single' slug=group.slug %}" class="mt-2 mb-2 btn btn-block">{{group.name}}</a>
    </div>
    {% endfor %}
  </div>

  <div class="row">
    <div class="col-lg-3 col-md-12">
      <!-- Card -->
      <div class="card">

        <!-- Card image -->
        <div class="view overlay">
          <img class="card-img-top"
            src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRKk3IsHFcgqQQmbnNAvcDnpzRmQVLv4o9S8wZKyNtRzky54-MU"
            alt="Card image cap">
          <a href="https://www.djangoproject.com/" target="_blank">
            <div class="mask rgba-white-slight"></div>
          </a>
        </div>

        <!-- Card content -->
        <div class="card-body">

          <!-- Title -->
          <h4 class="card-title">DJANGO</h4>
          <!-- Text -->
          <p class="card-text">Django is a high-level Python Web framework that encourages rapid development and clean,
            pragmatic design. Built by experienced developers, it takes care of much of the hassle of Web development,
            so
            you can focus on writing your app without needing to reinvent the wheel. It’s free and open source.</p>
          <!-- Button -->
          <a href="https://www.djangoproject.com/" target="_blank" id="django" class="btn btn-sm">Visit Django Docs</a>

        </div>

      </div>
      <!-- Card -->
    </div>

    <div class="col-lg-3">
      <!-- Card -->
      <div class="card mb-2">

        <!-- Card image -->
        <div class="view overlay">
          <img class="card-img-top"
            src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT9LcX0otYcolpJz6FRLf_ic-vsvSLUBpI29CObCQ00HHeibvCs"
            alt="Card image cap">
          <a href="https://flask-doc.readthedocs.io/en/latest/index.html" target="_blank">
            <div class="mask rgba-white-slight"></div>
          </a>
        </div>

        <!-- Card content -->
        <div class="card-body">

          <!-- Title -->
          <h4 class="card-title">FLASK</h4>
          <!-- Text -->
          <p class="card-text">Flask is a lightweight WSGI web application framework. It is designed to make getting
            started quick and easy, with the ability to scale up to complex applications. It began as a simple wrapper
            around Werkzeug and Jinja and has become one of the most popular Python web application frameworks.</p>
          <!-- Button -->
          <a href="https://flask-doc.readthedocs.io/en/latest/index.html" target="_blank"
            class="btn btn-sm waves-effect font-weight-bold">Read Flask Docs</a>

        </div>

      </div>
      <!-- Card -->
    </div>

    <div class="col-lg-3">
      <!-- Card -->
      <div class="card">

        <!-- Card image -->
        <div class="view overlay">
          <img class="card-img-top"
            src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTzTS-HzVFs7y-ZI-xTGY_gBVoONjEH6Ykoy0PLHMooJMLOhLyX"
            alt="Card image cap">
          <a href="https://www.python.org/doc/" target="_blank">
            <div class="mask rgba-white-slight"></div>
          </a>
        </div>

        <!-- Card content -->
        <div class="card-body">

          <!-- Title -->
          <h4 class="card-title">PYTHON</h4>
          <!-- Text -->
          <p class="card-text">Python is an object-oriented, high-level programming language with integrated dynamic
            semantics primarily for web and app development. It is extremely attractive in the field of Rapid
            Application
            Development because it offers dynamic typing and dynamic binding options.</p>
          <!-- Button -->
          <a href="https://www.python.org/doc/" target="_blank" class="btn btn-sm" id="python">Read Python Docs</a>

        </div>

      </div>
      <!-- Card -->
    </div>

    <div class="col-lg-3">
      <!-- Card -->
      <div class="card">

        <!-- Card image -->
        <div class="view overlay">
          <img class="card-img-top"
            src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRq8F-PS_dKm8S0VFnPg0syP21lDLbKfsbQChUbsfeIIr7m5E3r"
            alt="Card image cap">
          <a href="https://devdocs.io/javascript/" target="_blank">
            <div class="mask rgba-white-slight"></div>
          </a>
        </div>

        <!-- Card content -->
        <div class="card-body">

          <!-- Title -->
          <h4 class="card-title">JAVASCRIPT</h4>
          <!-- Text -->
          <p class="card-text">JavaScript is a scripting or programming language that allows you to implement complex
            features on web pages. Javascript enables you to create dynamically updating content, control multimedia,
            animate images. It is the language of the web.</p>
          <!-- Button -->
          <a href="https://devdocs.io/javascript/" target="_blank" class="btn btn-sm" id="js">Javascript Docs</a>

        </div>

      </div>
      <!-- Card -->
    </div>

  </div>
</div>

{% endblock %}