FriendFeed/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from groups import views
from questions import views as v


urlpatterns = [
    path('admin/', admin.site.urls),
	path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
	path('index/',TemplateView.as_view(template_name="index.html"), name="index"),
	path('',views.GroupList.as_view(),name='home'),
	path('groups/', include('groups.urls')),
	path('questions/', include('questions.urls')),
	path('create/question/', v.CreateQuestion.as_view(), name='create_question'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views
from questions import views as v
from django.conf import settings
from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),
         name='login'), 
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.Signup.as_view(), name='signup'),
    path('<slug>/', v.UserProfileQuestion, name='profile'),
    #path('<slug>/', v.UserProfile.as_view(), name='profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

groups/urls.py
from django.urls import path
from groups import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'groups'

urlpatterns = [
    path('<slug>/', views.GroupDetail.as_view(), name='single'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

questions/urls.py
from django.urls import path
from questions import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'questions'

urlpatterns = [
    path('detail/<slug>/', views.QuestionDetail.as_view(), name='question_single'),
    path('<slug>/delete/', views.DeleteQuestion.as_view(), name='delete_question'),
    path('<slug>/update/', views.UpdateQuestion.as_view(), name='update_question'),
    path('remove/answer/<pk>/', views.DeleteAnswer.as_view(), name='remove_answer'),
    path('<slug>/solved', views.question_solved, name='question_solved'),
    path('answer/<pk>/upvote', views.upvote, name='upvote'),
    path('answer/<pk>', views.DetailAnswer.as_view(), name='ans_single'),
    path('results/', views.SearchQuests, name="search_quests"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>FriendFeed</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.11/css/mdb.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Special+Elite&display=swap" rel="stylesheet">
  <link rel="stylesheet"  href="{% static 'css/main.css' %}">
</head>

<body>

  {% include 'navbar.html' %}

  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  <!-- JQuery -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.11/js/mdb.min.js"></script>
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<body style="background-image: url(https://images.pexels.com/photos/956981/milky-way-starry-sky-night-sky-star-956981.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500);">

<div class="container">

  <div class="row">
    {% for group in group_list %}
    <div class="col-lg-3 col-md-12 text-center" id="groups-list">
      <a href="{% url 'groups:single' slug=group.slug %}" class="mt-2 mb-2 btn btn-block">{{group.name}}</a>
    </div>
    {% endfor %}
  </div>

  <div class="row">
    <div class="col-lg-3 col-md-12">
      <!-- Card -->
      <div class="card">

        <!-- Card image -->
        <div class="view overlay">
          <img class="card-img-top"
            src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRKk3IsHFcgqQQmbnNAvcDnpzRmQVLv4o9S8wZKyNtRzky54-MU"
            alt="Card image cap">
          <a href="https://www.djangoproject.com/" target="_blank">
            <div class="mask rgba-white-slight"></div>
          </a>
        </div>

        <!-- Card content -->
        <div class="card-body">

          <!-- Title -->
          <h4 class="card-title">DJANGO</h4>
          <!-- Text -->
          <p class="card-text">Django is a high-level Python Web framework that encourages rapid development and clean,
            pragmatic design. Built by experienced developers, it takes care of much of the hassle of Web development,
            so
            you can focus on writing your app without needing to reinvent the wheel. It’s free and open source.</p>
          <!-- Button -->
          <a href="https://www.djangoproject.com/" target="_blank" id="django" class="btn btn-sm">Visit Django Docs</a>

        </div>

      </div>
      <!-- Card -->
    </div>

    <div class="col-lg-3">
      <!-- Card -->
      <div class="card mb-2">

        <!-- Card image -->
        <div class="view overlay">
          <img class="card-img-top"
            src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT9LcX0otYcolpJz6FRLf_ic-vsvSLUBpI29CObCQ00HHeibvCs"
            alt="Card image cap">
          <a href="https://flask-doc.readthedocs.io/en/latest/index.html" target="_blank">
            <div class="mask rgba-white-slight"></div>
          </a>
        </div>

        <!-- Card content -->
        <div class="card-body">

          <!-- Title -->
          <h4 class="card-title">FLASK</h4>
          <!-- Text -->
          <p class="card-text">Flask is a lightweight WSGI web application framework. It is designed to make getting
            started quick and easy, with the ability to scale up to complex applications. It began as a simple wrapper
            around Werkzeug and Jinja and has become one of the most popular Python web application frameworks.</p>
          <!-- Button -->
          <a href="https://flask-doc.readthedocs.io/en/latest/index.html" target="_blank"
            class="btn btn-sm waves-effect font-weight-bold">Read Flask Docs</a>

        </div>

      </div>
      <!-- Card -->
    </div>

    <div class="col-lg-3">
      <!-- Card -->
      <div class="card">

        <!-- Card image -->
        <div class="view overlay">
          <img class="card-img-top"
            src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTzTS-HzVFs7y-ZI-xTGY_gBVoONjEH6Ykoy0PLHMooJMLOhLyX"
            alt="Card image cap">
          <a href="https://www.python.org/doc/" target="_blank">
            <div class="mask rgba-white-slight"></div>
          </a>
        </div>

        <!-- Card content -->
        <div class="card-body">

          <!-- Title -->
          <h4 class="card-title">PYTHON</h4>
          <!-- Text -->
          <p class="card-text">Python is an object-oriented, high-level programming language with integrated dynamic
            semantics primarily for web and app development. It is extremely attractive in the field of Rapid
            Application
            Development because it offers dynamic typing and dynamic binding options.</p>
          <!-- Button -->
          <a href="https://www.python.org/doc/" target="_blank" class="btn btn-sm" id="python">Read Python Docs</a>

        </div>

      </div>
      <!-- Card -->
    </div>

    <div class="col-lg-3">
      <!-- Card -->
      <div class="card">

        <!-- Card image -->
        <div class="view overlay">
          <img class="card-img-top"
            src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRq8F-PS_dKm8S0VFnPg0syP21lDLbKfsbQChUbsfeIIr7m5E3r"
            alt="Card image cap">
          <a href="https://devdocs.io/javascript/" target="_blank">
            <div class="mask rgba-white-slight"></div>
          </a>
        </div>

        <!-- Card content -->
        <div class="card-body">

          <!-- Title -->
          <h4 class="card-title">JAVASCRIPT</h4>
          <!-- Text -->
          <p class="card-text">JavaScript is a scripting or programming language that allows you to implement complex
            features on web pages. Javascript enables you to create dynamically updating content, control multimedia,
            animate images. It is the language of the web.</p>
          <!-- Button -->
          <a href="https://devdocs.io/javascript/" target="_blank" class="btn btn-sm" id="js">Javascript Docs</a>

        </div>

      </div>
      <!-- Card -->
    </div>

  </div>
</div>

<!-- Footer -->
<footer class="page-footer font-small special-color-dark pt-4" style="padding-top: 20px;">

  <!-- Footer Elements -->

    <!-- Social buttons -->
    <ul class="list-unstyled list-inline text-center">
      <li class="list-inline-item">
        <a href="https://twitter.com/home" target="_blank" class="btn-floating btn-tw mx-1">
          <i class="fab fa-twitter"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a href="https://www.linkedin.com/feed/" target="_blank" class="btn-floating btn-li mx-1">
          <i class="fab fa-linkedin-in"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a href="https://www.linkedin.com/feed/" target="_blank" class="btn-floating btn-li mx-1">
          <i class="fab fa-facebook"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a href="https://www.linkedin.com/feed/" target="_blank" class="btn-floating btn-li mx-1">
          <i class="fab fa-instagram"> </i>
        </a>
      </li>
    </ul>
    <!-- Social buttons -->
  <!-- Footer Elements -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2019 Copyright:
    <a href="https://github.com/collinsbett29">Collins K. Bett</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->
</body>
{% endblock %}

templates/navbar.html
<!--Navbar-->
<nav class="navbar sticky-top navbar-expand-lg navbar-light mb-2 nav-font" style="background-color: white;">
  {% if user.is_authenticated %}
  <a class="navbar-brand" href="{% url 'home' %}">FriendFeed</a>
  {% else %}
  <a class="navbar-brand" href="{% url 'index' %}">FriendFeed</a>
  {% endif %}
    <!-- Navbar brand -->
  
    <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
      aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="basicExampleNav">
  
      <!-- Links -->
      <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'create_question' %}">Ask a Question</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}">Log Out
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Log In</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
        </li>
        {% endif %}
      </ul>
      <!-- Links -->
  
      <form class="form-inline" method="GET" action="{% url 'questions:search_quests' %}">
        <div class="md-form my-0">
          <input class="form-control mr-sm-2" type="search" name='q' placeholder="Search Questions" aria-label="Search">
        </div>
      </form>
    </div>
    <!-- Collapsible content -->
  
  </nav>
  <!--/.Navbar-->